### Create Category 100 - Guitars
POST http://localhost:3000/addcategory.test.php
Content-Type: application/x-www-form-urlencoded

categoryID=100
&categoryCode=GTR
&categoryName=Guitars

### Create Category 200 - Bass
POST http://localhost:3000/addcategory.test.php
Content-Type: application/x-www-form-urlencoded

categoryID=200
&categoryCode=BASS
&categoryName=Bass

### Create Category 300 - Electric
POST http://localhost:3000/addcategory.test.php
Content-Type: application/x-www-form-urlencoded

categoryID=300
&categoryCode=ELEC
&categoryName=Electric

### Create Category 400 - Acoustic
POST http://localhost:3000/addcategory.test.php
Content-Type: application/x-www-form-urlencoded

categoryID=400
&categoryCode=ACOS
&categoryName=Acoustic

### List all categories
GET http://localhost:3000/listcategories.test.php